# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TimeTableService_pb2 as TimeTableService__pb2


class TimetableProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimetable = channel.unary_unary(
                '/SuaiTimetable.TimetableProvider/GetTimetable',
                request_serializer=TimeTableService__pb2.TimetableRequest.SerializeToString,
                response_deserializer=TimeTableService__pb2.TimetableReply.FromString,
                )


class TimetableProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTimetable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimetableProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimetable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimetable,
                    request_deserializer=TimeTableService__pb2.TimetableRequest.FromString,
                    response_serializer=TimeTableService__pb2.TimetableReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SuaiTimetable.TimetableProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimetableProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTimetable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SuaiTimetable.TimetableProvider/GetTimetable',
            TimeTableService__pb2.TimetableRequest.SerializeToString,
            TimeTableService__pb2.TimetableReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
